name: 'lab08'
version: '1.0.0'
config-version: 2

profile: 'lab08'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  lab08:
    silver:
      +materialized: incremental
      +file_format: hudi
      +incremental_strategy: merge
      +schema: silver
      +location_root: s3a://lake/silver
      transactions_clean:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.clustering.inline: "true"
          hoodie.clustering.inline.max.commits: "4"
          hoodie.clustering.plan.strategy.target.file.max.bytes: "134217728"
          hoodie.clustering.plan.strategy.small.file.limit: "104857600"
          hoodie.clustering.plan.strategy.sort.columns: event_day
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day,is_test_user
      cancellations_clean:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.clustering.inline: "true"
          hoodie.clustering.inline.max.commits: "4"
          hoodie.clustering.plan.strategy.target.file.max.bytes: "134217728"
          hoodie.clustering.plan.strategy.small.file.limit: "104857600"
          hoodie.clustering.plan.strategy.sort.columns: event_day
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day
      exchange_rates_daily:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: rate_day
      exchange_rates_long:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: rate_day,currency
    gold:
      +materialized: incremental
      +file_format: hudi
      +incremental_strategy: merge
      +schema: gold
      +location_root: s3a://lake/gold
      transactions_by_hour:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day,hour_of_day,is_test_user
      purchases_by_hour:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day,hour_of_day
      revenue_daily:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day
      refunds_daily:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: cancel_day
      cancellations_summary:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: cancel_day
      promo_codes_analysis:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
      user_cohorts:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
      promo_expired_usage_daily:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day
      dq_summary_daily:
        +tblproperties:
          hoodie.parquet.compression.codec: zstd
          hoodie.clean.policy: KEEP_LATEST_COMMITS
          hoodie.clean.commits.retained: "2"
          hoodie.clean.automatic: "true"
          hoodie.clean.async.enabled: "true"
          hoodie.keep.min.commits: "4"
          hoodie.keep.max.commits: "5"
          hoodie.archive.automatic: "false"
          hoodie.metadata.enable: "true"
          hoodie.metadata.index.column.stats.enable: "true"
          hoodie.metadata.index.column.stats.column.list: event_day

vars:
  base_currency: "TGRK"
