lab08:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift-server.spark-jobs.svc.cluster.local
      port: 10000
      user: dbt
      schema: silver
      threads: 2
      connect_retries: 5
      connect_timeout: 60
      retry_all: true
