---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-tenant
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: lab08-observability
spec:
  namespaceSelector:
    matchNames:
      - storage
  selector:
    matchLabels:
      v1.min.io/tenant: lab08
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/cluster
      interval: 30s
      scheme: http
    - port: http-minio
      path: /minio/v2/metrics/node
      interval: 30s
      scheme: http
    - port: http-minio
      path: /minio/v2/metrics/bucket
      interval: 30s
      scheme: http
