repositories:
  - name: minio-operator
    url: https://operator.min.io
  - name: spark-operator
    url: https://kubeflow.github.io/spark-operator
  - name: apache-airflow
    url: https://airflow.apache.org
  - name: trino
    url: https://trinodb.github.io/charts
  - name: superset
    url: https://apache.github.io/superset
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.11.0"
    createNamespace: true
    values:
      - helm-values/ingress-nginx.yaml
  - name: minio-operator
    namespace: minio-operator
    chart: minio-operator/operator
    version: "6.0.4"
    createNamespace: true

  - name: minio-tenant
    namespace: storage
    chart: minio-operator/tenant
    version: "6.0.4"
    needs:
      - minio-operator/minio-operator
    values:
      - helm-values/minio-tenant.yaml

  - name: hive-metastore-postgres
    namespace: data-platform
    chart: bitnami/postgresql
    version: "15.5.38"
    values:
      - helm-values/hms-postgres.yaml

  - name: spark-operator
    namespace: data-platform
    chart: spark-operator/spark-operator
    version: "1.4.6"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "-n"
          - "data-platform"
          - "delete"
          - "secret"
          - "spark-operator-webhook-certs"
          - "--ignore-not-found"
    values:
      - helm-values/spark-operator.yaml

  - name: airflow
    namespace: data-platform
    chart: apache-airflow/airflow
    version: "1.15.0"
    needs:
      - data-platform/spark-operator
      - ingress-nginx/ingress-nginx
    values:
      - helm-values/airflow.yaml

  - name: trino
    namespace: data-platform
    chart: trino/trino
    version: "0.34.0"
    needs:
      - data-platform/hive-metastore-postgres
    values:
      - helm-values/trino.yaml

  - name: superset
    namespace: data-platform
    chart: superset/superset
    version: "0.13.2"
    needs:
      - data-platform/trino
      - ingress-nginx/ingress-nginx
    values:
      - helm-values/superset.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "65.5.1"
    createNamespace: true
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - helm-values/monitoring-stack.yaml

  - name: prometheus-statsd-exporter
    namespace: monitoring
    chart: prometheus-community/prometheus-statsd-exporter
    version: "0.13.0"
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - helm-values/statsd-exporter.yaml
