---
apiVersion: v1
kind: Secret
metadata:
  name: lab08-env-configuration
  namespace: storage
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="minioadmin"
    export MINIO_ROOT_PASSWORD="CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: lab08-credentials
  namespace: spark-jobs
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  AWS_ENDPOINT_URL: "http://minio.storage.svc.cluster.local"
  HMS_URIS: "thrift://hive-metastore.data-platform.svc.cluster.local:9083"
  KAFKA_BOOTSTRAP_SERVERS: "TODO_KAFKA_HOST:9092"
  KAFKA_TOPIC: "lab08_transactions"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: data-platform
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  AWS_ENDPOINT_URL: "http://minio.storage.svc.cluster.local"
