---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: bronze-reference-batch
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: lab08/spark:3.5.8-hudi-1.1.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/jobs/bronze_reference_batch.py"
  arguments:
    - "--reference-path=s3a://npl-de18-lab8-data/reference/"
  sparkVersion: "3.5.8"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 30
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 30
  timeToLiveSeconds: 10
  sparkConf:
    "spark.sql.catalogImplementation": "hive"
    "spark.sql.warehouse.dir": "s3a://lake/warehouse/"
    "spark.sql.extensions": "org.apache.spark.sql.hudi.HoodieSparkSessionExtension"
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
    "spark.kryo.registrator": "org.apache.spark.HoodieSparkKryoRegistrar"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.hudi.catalog.HoodieCatalog"
    "spark.hadoop.hive.metastore.uris": "thrift://hive-metastore.data-platform.svc.cluster.local:9083"
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.endpoint": "https://storage.yandexcloud.net"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.path.style.access": "true"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.connection.ssl.enabled": "true"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.aws.credentials.provider": "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
    "spark.kubernetes.namespace": "spark-jobs"
    "spark.kubernetes.executor.deleteOnTermination": "true"
    "spark.kubernetes.driverEnv.PYTHONPATH": "/opt/spark/jobs"
    "spark.executorEnv.PYTHONPATH": "/opt/spark/jobs"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    labels:
      app: bronze-reference-batch
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: lab08-credentials
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: lab08-credentials
        key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: jobs-code
        mountPath: /opt/spark/jobs
      - name: spark-utils-code
        mountPath: /opt/spark/jobs/utils
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      app: bronze-reference-batch
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: lab08-credentials
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: lab08-credentials
        key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: jobs-code
        mountPath: /opt/spark/jobs
      - name: spark-utils-code
        mountPath: /opt/spark/jobs/utils
  volumes:
    - name: jobs-code
      configMap:
        name: spark-jobs-code
    - name: spark-utils-code
      configMap:
        name: spark-utils-code
