---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: bronze-s3-streaming
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: lab08/spark:3.5.8-hudi-1.1.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/jobs/bronze_s3_streaming.py"
  arguments:
    - "--transactions-path=s3a://npl-de18-lab8-data/day=*/slot=*/"
    - "--cancellations-path=s3a://npl-de18-lab8-data/cancellations/"
    - "--rates-path=s3a://npl-de18-lab8-data/exchange_rates/"
    - "--ckpt-root=s3a://checkpoints/bronze-s3-stream-yc"
  deps:
    pyFiles:
      - "local:///opt/spark/jobs/log_utils.py"
      - "local:///opt/spark/jobs/hudi_utils.py"
      - "local:///opt/spark/jobs/hudi_commit_meta.py"
      - "local:///opt/spark/jobs/watermark_utils.py"
  sparkVersion: "3.5.8"
  restartPolicy:
    type: Always
    onFailureRetries: 10
    onFailureRetryInterval: 30
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 30
  sparkConf:
    "spark.sql.catalogImplementation": "hive"
    "spark.sql.warehouse.dir": "s3a://lake/warehouse/"
    "spark.sql.extensions": "org.apache.spark.sql.hudi.HoodieSparkSessionExtension"
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
    "spark.kryo.registrator": "org.apache.spark.HoodieSparkKryoRegistrar"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.hudi.catalog.HoodieCatalog"
    "spark.hadoop.hive.metastore.uris": "thrift://hive-metastore.data-platform.svc.cluster.local:9083"
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.endpoint": "https://storage.yandexcloud.net"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.path.style.access": "true"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.connection.ssl.enabled": "true"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.aws.credentials.provider": "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
    "spark.kubernetes.namespace": "spark-jobs"
    "spark.kubernetes.executor.deleteOnTermination": "true"
    "spark.sql.shuffle.partitions": "8"
    "spark.sql.streaming.numRecentProgressUpdates": "20"
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.minPartitionSize": "8m"
    "spark.sql.adaptive.advisoryPartitionSizeInBytes": "32m"
    "spark.scheduler.mode": "FAIR"
    "spark.sql.streaming.fileSource.log.compactInterval": "10"
    "spark.sql.streaming.fileSource.log.cleanupDelay": "1800000"
    "spark.sql.streaming.minBatchesToRetain": "10"
    "spark.memory.offHeap.enabled": "true"
    "spark.memory.offHeap.size": "512m"
    "spark.memory.fraction": "0.5"
    "spark.shuffle.file.buffer": "32k"
    "spark.shuffle.spill.compress": "true"
    "spark.rdd.compress": "true"
    "spark.cleaner.periodicGC.interval": "30s"
    "spark.hadoop.fs.s3a.connection.maximum": "64"
    "spark.hadoop.fs.s3a.threads.max": "16"
    "spark.hadoop.fs.s3a.list.version": "2"
    "spark.hadoop.fs.s3a.experimental.input.fadvise": "sequential"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.connection.maximum": "64"
    "spark.hadoop.fs.s3a.bucket.npl-de18-lab8-data.threads.max": "16"
    "spark.hadoop.fs.s3a.fast.upload.buffer": "disk"
    "spark.hadoop.fs.s3a.multipart.size": "32M"
    "spark.hadoop.fs.s3a.fast.upload.active.blocks": "2"
    "spark.metrics.namespace": "spark"
    "spark.sql.streaming.metricsEnabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.*.sink.prometheusServlet.path": "/metrics/prometheus/"
    "spark.metrics.conf.master.sink.prometheusServlet.path": "/metrics/master/prometheus/"
    "spark.metrics.conf.applications.sink.prometheusServlet.path": "/metrics/applications/prometheus/"
    "spark.metrics.conf.driver.source.jvm.class": "org.apache.spark.metrics.source.JvmSource"
    "spark.metrics.conf.executor.source.jvm.class": "org.apache.spark.metrics.source.JvmSource"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    memoryOverhead: "256m"
    serviceAccount: spark
    labels:
      app: bronze-s3-streaming
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: lab08-credentials
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: lab08-credentials
        key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: jobs-code
        mountPath: /opt/spark/jobs
  executor:
    cores: 1
    instances: 3
    memory: "2g"
    memoryOverhead: "1536m"
    labels:
      app: bronze-s3-streaming
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: lab08-credentials
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: lab08-credentials
        key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: jobs-code
        mountPath: /opt/spark/jobs
  volumes:
    - name: jobs-code
      configMap:
        name: spark-jobs-code
